[package]
name = "kcimpl"
version = "0.1.0"
edition = "2021"

[dependencies]
sha3 = "0.10.8"
digest = "0.9.0"
rand = "0.8.5"
reed-solomon-erasure = "=6.0.0"
labrador-ldpc="1.2.1"

[dev-dependencies]
criterion = "0.3"


[[bench]]
name = "kyber-bench"
path = "benches/kyber-bench.rs"
harness = false
